layout_spectrum: 0.9390709
typography_spectrum: 0.8691756
color:
  saturation: 0.5017921
  lightness: 0.7329749
  brandStrength: 0.5340502
  brandColors:
    - '#FFFFFF'
    - '#4D4D4D'
    - '#7D6460'
    - '#DEC0A8'
    - '#33282C'
  rhythmicContrast: 0.2943867
name: Beatrice Plaiche
