layout_spectrum: 0.9390709
color:
  saturation: 0.6191731
  lightness: 0.7354873
  brandStrength: 0.5356374
  brandColors:
    - '#FFFFFF'
    - '#4D4D4D'
    - '#7D6460'
    - '#DEC0A8'
    - '#33282C'
  rhythmicContrast: 0.2943867
typography_spectrum: 0.2776219
name: Beatrice Plaiche
